# Generated by Django 5.0.2 on 2024-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tanks',
            fields=[
                ('tank_no', models.IntegerField(primary_key=True, serialize=False)),
                ('owt_tank_name', models.CharField(max_length=255)),
                ('owt_address', models.CharField(max_length=255)),
                ('owt_position', models.CharField(max_length=255)),
                ('owt_tank_shape', models.CharField(max_length=255)),
                ('owt_dimension_cm', models.CharField(max_length=255)),
                ('inlet_pip', models.CharField(max_length=255)),
                ('inlet_pip_size_cm', models.CharField(max_length=255)),
                ('outlet_pip', models.CharField(max_length=255)),
                ('outlet_pip_size_cm', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
    ]
