# Generated by Django 4.2.7 on 2024-02-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_tanks_inlet_pip_alter_tanks_inlet_pip_size_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
