# Generated by Django 5.0.2 on 2024-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
