# Generated by Django 5.0.2 on 2024-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_marker_type_alter_marker_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
