# Generated by Django 5.0.2 on 2024-02-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_marker_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='path_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='point_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
