# Generated by Django 5.0.2 on 2024-02-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_marker_pip_dimeter_marker_pip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='pip_dimeter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='pip_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
