# Generated by Django 5.0.2 on 2024-03-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_marker_pip_dimeter_alter_marker_pip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='valve_diameter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='valve_key_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='valve_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
