# Generated by Django 5.0.2 on 2024-03-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_marker_valve_diameter_marker_valve_key_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='pip_type',
            new_name='pip_material',
        ),
    ]
