# Generated by Django 5.0.2 on 2024-03-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_pip_type_marker_pip_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='pip_dimeter',
            new_name='pip_diameter',
        ),
    ]
