# Generated by Django 5.0.2 on 2024-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_pip_dimeter_marker_pip_diameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='jw',
            fields=[
                ('jw_no', models.IntegerField(primary_key=True, serialize=False)),
                ('jw_name', models.CharField(blank=True, max_length=255, null=True)),
                ('jw_address', models.CharField(blank=True, max_length=255, null=True)),
                ('jw_position', models.CharField(blank=True, max_length=255, null=True)),
                ('jw_shape', models.CharField(blank=True, max_length=255, null=True)),
                ('jw_dimension_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('inlet_pip', models.CharField(blank=True, max_length=255, null=True)),
                ('inlet_pip_size_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_pip', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_pip_size_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
