# Generated by Django 5.0.2 on 2024-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_jw'),
    ]

    operations = [
        migrations.CreateModel(
            name='booster',
            fields=[
                ('booster_no', models.IntegerField(primary_key=True, serialize=False)),
                ('booster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('booster_address', models.CharField(blank=True, max_length=255, null=True)),
                ('booster_position', models.CharField(blank=True, max_length=255, null=True)),
                ('booster_shape', models.CharField(blank=True, max_length=255, null=True)),
                ('booster_dimension_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('inlet_pip', models.CharField(blank=True, max_length=255, null=True)),
                ('inlet_pip_size_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_pip', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_pip_size_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wtp',
            fields=[
                ('wtp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('wtp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wtp_address', models.CharField(blank=True, max_length=255, null=True)),
                ('wtp_position', models.CharField(blank=True, max_length=255, null=True)),
                ('wtp_shape', models.CharField(blank=True, max_length=255, null=True)),
                ('wtp_dimension_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('inlet_pip', models.CharField(blank=True, max_length=255, null=True)),
                ('inlet_pip_size_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_pip', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_pip_size_cm', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
